[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "no-redzone",
    "-C", "relocation-model=static",
]

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
